version: '3.8'
services:
  db:
    image: mysql:9.4.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - devdojo_maratona_data:/var/lib/mysql

volumes:
  devdojo_maratona_data: